### ISSUE TITLE
Document "TODO" for storage configuration parameter in the packages section

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [verdaccio/website#16]
In https://github.com/verdaccio/website/blob/master/docs/packages.md there is still a TODO in the bottom table for parameters.

I set up a Verdaccio registry recently and thought I had to switch this to `true` because I wanted some scoped packages to be stored. But setting this to `true` caused `npm publish` to fail (404 error).

So it would be nice to add documentation for this parameter (or remove it as long as it's not described what it does).

**Comment by juanpicado** [comment]
hi @FrontierPsychiatrist which parameter? Could you share an example?

**Comment by FrontierPsychiatrist** [comment]
Hey, sure!

```
packages:
  '@somescope/*':
    access: $all
    publish: $authenticated
    storage: true
```

This boolean is documented with TODO on the page I linked, in the table at the bottom.
